# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a31ee4fc6dc957e9dfb08c1c049a6a4a107e95974d84095c78140cdb69d652c0a3931b726d3ce8067d92e39a583ddb6aa8dabce93d9268be39ca4c89349c6c9e

test:
  secret_key_base: 50785990a1309049e0d02bce7417851d2b948f201572e0df16aa063cc9d7bd37c6fa67f7e19ce2a881003df702b439b486f7d65a93cc5d961d0bed7741590d44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
